// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8Sh0kyl0lvvhTKb8SEpAHgGL9zxiby8s',
    appId: '1:443675054724:web:14655dde39305fe6b168d1',
    messagingSenderId: '443675054724',
    projectId: 'retailshoes-96a15',
    authDomain: 'retailshoes-96a15.firebaseapp.com',
    storageBucket: 'retailshoes-96a15.appspot.com',
    measurementId: 'G-5X11MKD6L4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9Cs-dSKP7gVBzA205VGmF1hAfJBIN01U',
    appId: '1:443675054724:android:4ade696e350323a7b168d1',
    messagingSenderId: '443675054724',
    projectId: 'retailshoes-96a15',
    storageBucket: 'retailshoes-96a15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgx--BJBuHAN4i01oLz8iaAAKqtGQwRzo',
    appId: '1:443675054724:ios:9adcbb1de2fb10d9b168d1',
    messagingSenderId: '443675054724',
    projectId: 'retailshoes-96a15',
    storageBucket: 'retailshoes-96a15.appspot.com',
    iosClientId:
        '443675054724-nv41mq40vfk7n3gohj4hlf8grpsi7rih.apps.googleusercontent.com',
    iosBundleId: 'com.example.retailShoes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgx--BJBuHAN4i01oLz8iaAAKqtGQwRzo',
    appId: '1:443675054724:ios:acb36ca0671d8b0ab168d1',
    messagingSenderId: '443675054724',
    projectId: 'retailshoes-96a15',
    storageBucket: 'retailshoes-96a15.appspot.com',
    iosClientId:
        '443675054724-2r4r7srbp1d5fpvs44rlarp8q1uj8sus.apps.googleusercontent.com',
    iosBundleId: 'com.example.retailShoes.RunnerTests',
  );
}
